Updated Deus ex Machina and Setup
RoboCupAtHome/RuleBook pull request #785
Opened 2023-03-29 10:06 UTC by ARTenshi

Updated the definitions in Deus ex Machina section to avoid fixed scoring regulations and leave those to the specificites of each task and their own scoring systems.

Also, commented out the Welcome Reception subsection as it is not a technical aspect to be regulated in this rulebook. It has been left opened in case the EC strongly suggest to get it back.

2023-03-29 11:26 UTC, PetervDooren requested changes
Regarding the score reduction I still have a few points: 
1. are the percentages still consistent with the rulebook?
2.  I think it might be a good idea to give indications of how much reduction should be given. For when we are making scoresheets for future tests.

2023-03-29 11:26 UTC, PetervDooren commented on Setup.tex
> +% It is still open for the TC to get it back is the EC strongly request it
Lets add a timestamp so we know when this decision was made
```suggestion
% It is left commented for the TC to get it back is the EC strongly request it. 2023
```

2023-03-29 11:39 UTC, ARTenshi commented
I agree but it requires a further discussion ans consensus that might not happen in the next couple of days.

2023-03-30 09:05 UTC, ARTenshi commented
It should be done before releasing the scores as, if it becomes a general guideline, we should check all scoring sheets comply with it (and, by modifying the Deus ex Machina sections, we should check the final sums and modify other scores and so on). As it is written now, each "Deus ex Machina" section follows its own considerations.

2023-04-14 07:22 UTC, PetervDooren commented
The way this PR is currently written there is no difference between the different deus ex machinas. Whereas the latter should be more heavily penalised than the first ones. I would still like to see an indication of how severely these are penalised, even if we do not want to give a numeric amount.

2023-05-02 21:41 UTC, closed without merging