German Open Feedback for Carry my Luggage
RoboCupAtHome/RuleBook pull request #864
Opened 2024-04-23 13:01 UTC by johaq

- Adding penalty for rediscovering the operator by asking them to come back
- Clarify the DEM penalties are only applied if the robot scores afterwards

2024-04-23 13:21 UTC, LeroyR requested changes

2024-04-23 13:21 UTC, LeroyR commented on tasks/CarryMyLuggage.tex
> +	Note: Penalties for human assistance are only applied if the robot continues to score after the interaction.
Can the penalties be applied multiple times? How do different DEM penalties stack - (e.g. up to XXXpts penalty) We should specify that.

Id suggest something like " Penalties can be applied multiple times upto a total of 250points" 
As the latest results suggest the task is still pretty hard

2024-04-23 14:09 UTC, LeroyR approved these changes

2024-05-03 12:17 UTC, akinobu1998 approved these changes

2024-05-03 12:24 UTC, hawkina approved these changes

2024-05-03 12:39 UTC, merged