German Open Feedback for EGPSR
RoboCupAtHome/RuleBook pull request #868
Opened 2024-04-23 13:42 UTC by johaq

- Clarify what Find and clearly state an encountered problem means for people requesting assistance
- Allow partial points for understanding commands

2024-04-23 14:09 UTC, LeroyR requested changes

2024-04-23 14:09 UTC, LeroyR commented on tasks/EGPSR.tex
> +	\item \textbf{Understanding Commands:} Understanding and and correctly repeating the command given by a person can be counted towards partially solving a problem.
```suggestion
	\item \textbf{Understanding Commands:} Understanding and correctly repeating the command given by a person can be counted towards partially solving a problem.
```

2024-04-24 11:56 UTC, LeroyR approved these changes

2024-05-03 12:15 UTC, akinobu1998 approved these changes

2024-05-03 12:30 UTC, hawkina approved these changes

2024-05-03 12:38 UTC, akinobu1998 commented
Do we resume a timer like #865?

2024-05-03 12:41 UTC, johaq commented
> Do we resume a timer like #865?

No,  all the challenges for the robot should already be setup in the arena when the robot enters. So the robot can just immediately continue looking for new things to do

2024-05-03 12:48 UTC, merged