Restart of the robot during challange
RoboCupAtHome/RuleBook pull request #921
Opened 2024-11-25 12:02 UTC by sunava

Closes issue [898](https://github.com/RoboCupAtHome/RuleBook/issues/898)

Changes proposed in this pull request:

Introduced a rule allowing teams to request a single restart per attempt with specific conditions, including a 30-second penalty.
Clarified the restart procedure: teams must leave the arena with the robot, requeue, and begin again within their remaining time.
Added a provision to include a restart checkbox in the score sheet for tracking.
Other comments

Feedback is particularly requested on:

Whether the 30-second penalty and "remaining time" provision are balanced for both DSPL and OPL leagues.
Placement of the rule within the Rulebook (e.g., procedural rules, scoring, or test-specific rules).
Additional details for score sheet implementation.

2024-11-25 12:29 UTC, LeroyR requested changes
- Add checkbox to scroing, remove Score sheet adjustment header :smile: 
- Entering arena already gives points - reword to major score item or simply limit to first _X_ sec (60?) of attempt.
- move the _penalty_ item after _time continues running_ or combine them `..exited the \Arena{} with the robot and an extra penalty...`
- Add that only the points earned after the restart are counted

2024-11-25 12:33 UTC, LeroyR commented
Add checkbox below 

https://github.com/RoboCupAtHome/RuleBook/blob/f530a8036a1e5082abba6f95f71e834dfbc784a6/setup/macros_scoresheets.tex#L554

Maybe just:
```
\scoreitem{0}{Restart after (sec:)}
```
is fine

2024-11-25 12:59 UTC, johaq submitted a review, later dismissed

2024-11-25 12:59 UTC, johaq commented on pages/general_rules/Procedure.tex
> +    \item A restart incurs a penalty of \SI{30}{\second}, added to the total time.
Should be subtracted from the total time, no?

2024-11-25 12:59 UTC, johaq commented on pages/general_rules/Procedure.tex
> +\textbf{Score Sheet Adjustment:}
This does not need to be in the rules.
Just add the checkmark to the scoresheets

2024-12-09 10:52 UTC, sunava commented
what do you mean by: "move the penalty item after time continues running or combine them ..exited the \Arena{} with the robot and an extra penalty..." @LeroyR

2024-12-10 11:04 UTC, LeroyR commented
> what do you mean by: "move the penalty item after time continues running or combine them ..exited the \Arena{} with the robot and an extra penalty..." @LeroyR

Instead of:
```
 \item A restart incurs a penalty of \SI{30}{\second}, subtracted from the total time.
 \item The test time will continue running until the team has exited the \Arena{} with the robot.
```

I Prefer
```
 \item The test time will continue running until the team has exited the \Arena{} with the robot.
 \item A restart incurs a penalty of \SI{30}{\second}, subtracted from the total time.
```

Or Combine both item about time
```
 \item The test time will continue running until the team has exited the \Arena{} +30sec ...
```

2024-12-17 13:07 UTC, sunava commented
@johaq @LeroyR  done

2025-01-10 18:41 UTC, sunava commented
@LeroyR @johaq @hawkina @SparkRibeiro21 @akinobu1998  can you approve so i can merge pls

2025-01-10 18:55 UTC, LeroyR approved these changes

2025-01-10 18:55 UTC, LeroyR commented on pages/general_rules/Procedure.tex
> +    \item A restart may only be requested until the robot completes a major scoring action.
What is a major scoring item? 

In Storing groceries we have "reaching the table" as Main goal. Do we disallow restarts after that?

I am fine either way.

2025-01-10 18:55 UTC, LeroyR commented on pages/general_rules/Procedure.tex
> +    \item A restart incurs a penalty of \SI{30}{\second}, subtracted from the total time.
Subtracted from the total time is a bit confusing should be clear by the word penalty tho...

Maybe subtract from the time limit?

2025-01-11 16:15 UTC, akinobu1998 commented on pages/general_rules/Procedure.tex
> +    \item A restart may only be requested until the robot completes a major scoring action.
Just clarification,
> completes a major scoring action

means the robot attempts to solve a main goal task or acquire a point of a main goal task?

2025-01-11 20:06 UTC, SparkRibeiro21 approved these changes

2025-01-13 20:44 UTC, akinobu1998 commented
Feedback from the TC meeting on the 13th.

The original idea for restart is to give a chance for the teams that faces hardware trouble. We need to discuss this point.

2025-01-15 15:30 UTC, sunava commented
that's the whole point of this PR. Accordingly, you can only restart if you haven’t received any points yet.

2025-01-20 09:57 UTC, merged